# Generated by Django 3.1 on 2020-08-16 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('story', models.CharField(max_length=500)),
                ('time', models.TimeField(default=datetime.datetime(2020, 8, 16, 17, 33, 53, 200520))),
            ],
        ),
    ]
