# Generated by Django 3.1 on 2020-08-16 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='story',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 16, 17, 36, 6, 339754)),
        ),
    ]
