# Generated by Django 3.1 on 2020-08-17 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200816_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 17, 14, 47, 44, 173395)),
        ),
    ]
