# Generated by Django 3.1 on 2020-08-17 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200817_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='story',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 17, 19, 17, 16, 862940)),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
